# Generated by Django 6.0.1 on 2026-03-30 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishing",
            name="added_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phishing",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
